### PR TITLE
Make into package

### PR DESCRIPTION
**Pull request by gchers**
Hi,

This PR makes it possible to install `grobid_client` as a package. This implies the following changes:
- `python setup.py install` installs the package
- `grobid_client` can now be called directly as a command, after installing the package
- one can write stuff such as `from grobid_client.grobid_client import GrobidClient`.

I also updated the readme with new instructions. However, since it does change the way the script was initially wrote, eel free to accept/not accept, as you like.

This should fix issue #14

### CODE REVIEW

**Comment by mathias-goebel** [comment]
Hi. Here is just another guy from the internet confirming that this is a working increment. Special thanks to the author for editing the README.md as well.

**Comment by kermitt2** [comment]
Thank you very much @gchers once again for your contribution and this improvement, and @mathias-goebel from the internet for the confirmation! We started with a toy script to illustrate how to use the grobid service, and now we have a decent package.

**Comment by kermitt2** [comment]
@gchers two things:

- to get `test.py`working, the file has to be moved back to the root of the project, and updated as indicated in the readme:

```python
from grobid_client.grobid_client import GrobidClient

if __name__ == "__main__":
    client = GrobidClient(config_path="./config.json")
    client.process("processFulltextDocument", "./resources/test", output="./resources/test_out/", consolidate_citations=True, teiCoordinates=True, force=True)

``` 
 
(maybe it could be re-named rather `example.py`)

- could you merge maybe your PR with the current master? I made some modifications in master to avoid some syntax errors I observed with python 3.5. Otherwise I need to do a manual merge from your fork. 

Thanks !

**Comment by gchers** [comment]
Hi there!

I merged from upstream, adapted the `test.py` as you indicated, moved `test.py` to root (now it's called `example.py`), and adapted the readme (wherever I could find a mention of that file).

Let me know if you see any further breaking changes.

Cheers

**Comment by kermitt2** [comment]
Super, thank you @gchers !

**Pull request merged**
